name: linux

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v3
        - name: Setup Dependencies
        run: |
            apt-get update
            apt-get install -y \
            build-essential \
            cmake \
            ninja-build