name: linux
run-name: unit test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: update
        run: sudo apt-get update
      - name: install dependency
        run: sudo apt-get install build-essential cmake ninja-build libboost-all-dev libeigen3-dev

      - name: build unit test
        run: cmake -Btest/build -Stest -G Ninja && cmake --build test/build

      - name: run unit test
        run: test/build/unit_test.exe
