name: linux
run-name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependency
        uses: actions/checkout@v4
      - run: |
        apt-get update
        apt-get install -y \
        build-essential \
        cmake \
        ninja-build \
        apt-get install libboost-all-dev
      - name: build unit test
      -run: cmake -Btest/build -Stest
      -run: cmake --build test/build
      
