name: linux
run-name: unit test
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: update
        run: sudo apt-get update
      - name: install dependency
        run: sudo apt-get install build-essential cmake ninja-build libeigen3-dev

      - name: install boost library
        uses: MarkusJx/install-boost@v2.4.4
        id: install-boost
        with:
            boost_version: 1.83.0
            platform_version: 22.04
            boost_install_dir: /home/runner/boost_1_83_0

      - name: build unit test
        run: export BOOST_PATH=/home/runner/boost_1_83_0/boost/boost && cmake -DENABLE_EXCEPTION=ON -DENABLE_ASSERTION=ON -Btest/build -Stest -G Ninja && cmake --build test/build

      - name: run unit test
        run: test/build/bin/unit_test.exe
      
      - name: create pull request
        if: success()  # Only runs if previous steps succeeded
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Automated PR: Tests succeeded'
          branch: master
          title: 'Merge feature branch into master'
          body: 'Automated PR created after tests passed successfully.'
          labels: 'automated-pr'
