name: linux
run-name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: install dependency
        run: sudo apt-get update && \
             apt-get install -y \
             build-essential \
             cmake \
             ninja-build \
             libboost-all-dev

      - name: build unit test
        run: cmake -Btest/build -Stest -G Ninja && cmake --build test/build
      
