name: Promote
run-name: Promote
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:      
      - name: Update
        run: sudo apt-get update

      - name: Install dependency
        run: sudo apt-get install build-essential cmake ninja-build libeigen3-dev

      - name: Install boost library
        uses: MarkusJx/install-boost@v2.4.4
        id: install-boost
        with:
            boost_version: 1.83.0
            platform_version: 22.04
            boost_install_dir: /home/runner/boost_1_83_0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build unit test
        run: export BOOST_PATH=/home/runner/boost_1_83_0/boost/boost && cmake -DENABLE_EXCEPTION=ON -DENABLE_ASSERTION=ON -DENABLE_ASAN=ON -Btest/build -Stest -G Ninja && cmake --build test/build

      - name: Run unit test
        run: test/build/bin/unit_test.exe

      - name: Create pull request
        if: success()
        run: gh pr create -B master -H dev --title 'Merge dev into master' --body 'created by github action'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}