name: Update Documentation
run-name: Update Documentation
on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-22.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run doc-updater script
        run: python3 tools/doc-updater.py

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code README.md || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "docs: Update API documentation in README.md [skip ci]"
          git push
